name: johndoe_car
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^2.4.1

  # Language
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  # UI
  cupertino_icons: ^1.0.6

  # Helpers
  dartz: ^0.10.1
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  connectivity_plus: ^6.0.3

  # Dependency injection
  get_it: ^7.7.0
  injectable: ^2.4.2

  # Routing
  auto_route: ^8.1.3

  # State management system
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_gen: ^5.5.0+1
  flutter_gen_runner: ^5.5.0+1
  auto_route_generator: ^8.0.0
  injectable_generator: ^2.6.1
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600

flutter_gen:
  integrations:
    lottie: true

  colors:
    inputs:
      - assets/colors/colors.xml
